const parser = require('@babel/parser');
const traverse = require('@babel/traverse').default;
const types = require('@babel/types');
const generate = require('@babel/generator').default;
const fs = require('fs');
const path = require('path');

const sourceCode = fs.readFileSync(path.resolve(__dirname, './test_1.js'), {
  encoding: 'utf8'
});

const res = parser.parse(sourceCode, {
  sourceType: 'module',
  plugins: ['jsx', 'typescript']
});

const addAnnotations = (p, args) => {
  //   console.log(p.node.params);
  const annotations = ['*', '* this annotation is generated by Lester'];
  const params = args || p.node.params || [];
  params.forEach((node) => {
    annotations.push(`* @param {*} ${node.name}`);
  });
  //   annotations.push('* @param {*} testParam1');
  //   annotations.push('* @param {*} testParam2');
  annotations.push('');
  p.addComment('leading', annotations.join('\n'));
};

traverse(res, {
  VariableDeclaration(path) {
    if (path.node.kind === 'var') {
      path.node.kind = 'let';
    }
  },
  VariableDeclarator(p) {
    if (p.get('init').isArrowFunctionExpression()) {
      const params = p.get('init').node.params;
      const exportParent = p.findParent((p) => p.isExportNamedDeclaration());
      const variableParent = p.findParent((p) => p.isVariableDeclaration());
      if (exportParent) {
        addAnnotations(exportParent, params);
      } else if (variableParent) {
        addAnnotations(variableParent, params);
      }
      //   addAnnotations(p);
    }
    if (p.node.id.name === 'name') {
      p.node.init = types.numericLiteral(10);
      //   console.log(p.node);
    }
  },
  ClassMethod(p) {
    addAnnotations(p);
  },
  FunctionDeclaration(p) {
    addAnnotations(p);
  },
  ArrowFunctionExpression(p) {
    // addAnnotations(p);
    // console.dir(p.node, { depth: null });
  },
  DebuggerStatement(p) {
    p.remove();
  }
});

// code map
const output = generate(res, { sourceMaps: true }, sourceCode);

console.log(output.code);

// console.dir(res, { depth: null });
